# Generated by Django 3.1 on 2020-08-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='summary',
            field=models.CharField(default='summary', max_length=32),
        ),
    ]
