# Generated by Django 3.1 on 2020-08-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_main_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='catch_phrases',
            field=models.TextField(default='phrases-coma-seperated'),
        ),
    ]
