# Generated by Django 3.1 on 2020-08-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200830_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='foreign_k_pk',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
