# Generated by Django 3.1 on 2020-08-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slider_foreign_k_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='images',
            field=models.ImageField(upload_to='static/front/images/home/slider'),
        ),
    ]
