# Generated by Django 3.1 on 2020-08-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200830_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='images',
            field=models.ImageField(max_length=256, upload_to='home/slider'),
        ),
    ]
