# Generated by Django 3.1 on 2020-08-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200830_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_main_pk', models.CharField(default='0', max_length=4)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_main_pk', models.CharField(default='0', max_length=4)),
                ('foreign_ocassion_pk', models.CharField(default='0', max_length=4)),
                ('name', models.CharField(max_length=32)),
                ('keyword', models.CharField(max_length=256)),
                ('details', models.TextField(default='details')),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('brand', models.CharField(default='brand', max_length=256)),
                ('picture', models.ImageField(max_length=256, upload_to='home/products')),
            ],
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='foreign_k_pk',
            new_name='foreign_main_pk',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='images',
            new_name='picture',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='name',
        ),
        migrations.AddField(
            model_name='slider',
            name='foreign_ocassion_pk',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
