# Generated by Django 3.1 on 2020-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200830_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='foreign_main_pk',
            field=models.CharField(default='1', max_length=4),
        ),
    ]
