# Generated by Django 3.1 on 2020-08-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200830_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasion',
            name='foreign_main_pk',
            field=models.CharField(default='404', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='foreign_ocassion_pk',
            field=models.CharField(default='404', max_length=4),
        ),
    ]
