# Generated by Django 3.1 on 2020-08-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200830_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='foreign_ocassion_pk',
            field=models.CharField(default='4', max_length=4),
        ),
    ]
